### ISSUE TITLE
On HTTP Response Handling

### ISSUE THREAD

**Issue by cszichao** [haxii/fastproxy#12]
- [x] Transfer-Encoding's priority should be higher's than Content-Length
- [x] Write target and sniffer should be separated into concurrent go routines
- [x] Content-Type given to sniffer

**Comment by cszichao** [comment]
#13 Task `Content-Type given to sniffer` finished

**Comment by cszichao** [comment]
#15 Issue `Transfer-Encoding's priority should be higher's than Content-Length` fixed

**Comment by cszichao** [comment]
#16  Feature ` Write target and sniffer should be separated into concurrent go routines` finished
